name: Example changelog
on: 
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Clone repository
      run: git clone https://github.com/CodeDoctorDE/DoctorUtils.git
    - run: cd DoctorUtils/changelog-generator
    - name: Run a one-line script
      run: python main.py -o ../../changelog-generator/example.md LinowodCloud dev_doctor
    - name: switching from HTTPS to SSH
      run: git remote set-url origin ${{ secrets.ssh }}
    - name: check for changes
      run: git status
    - name: stage changed files
      run: git add changelog-generator/example.md
    - name: commit changed files
      run: git commit -m "Auto updating CHANGELOG.md"
    - name: fetch from main
      run: git fetch origin main
    - name: push code to main
      run: git push origin HEAD:main