name: Example changelog
on: 
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
    - name: Clone repository
      run: git clone https://github.com/CodeDoctorDE/DoctorUtils.git
    - name: Run a one-line script
      run: |
        cd DoctorUtils/changelog-generator
        python main.py -o ../../changelog-generator/example.md LinwoodCloud dev_doctor
    - name: check for changes
      run: |  
        git status
    - name: stage changed files
      run: git add changelog-generator/example.md
    - name: commit changed files
      run: git commit -m "Auto updating CHANGELOG.md"
    - name: fetch from main
      run: git fetch origin main
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true